# Generated by Django 2.2.4 on 2020-05-10 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('realtor_id', models.IntegerField()),
                ('listing_id', models.IntegerField()),
                ('content', models.CharField(max_length=200)),
                ('type', models.IntegerField()),
                ('is_published', models.BooleanField()),
                ('submit_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
