# Generated by Django 2.2.4 on 2020-05-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='listing_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='realtor_id',
            field=models.IntegerField(null=True),
        ),
    ]
