# Generated by Django 2.2.4 on 2020-05-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20200510_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
